folke/lazy.nvim

lua/lazy/view/init.lua

Add a filetype to the Lazy window buffer, which allows plugins like codewindow to ignore it.

Add filetype to window buffer.

---

lua/lazy/manage/checker.lua
lua/lazy/manage/task/git.lua

According to the docs when a plugin spec has the `pin` value as true then it doesn't participate in updates.
Thus, this patch ensures that no git checks are done for that plugin in case the `pin` option is set to true.
(no notifications or indications in the Lazy window about updates)

fix(checker): allow git checks only for non-pinned plugins

---

README.md

docs: 'cmd' repeat twice

---

lua/lazy/manage/init.lua

This PR updates the lockfile when executing the `clean` command.
Relates: #82

fix(clean): update lockfile on clean

---

lua/lazy/view/init.lua

Fix #81 
This fixes my issue. Check the comment on the issue for my finding on `vim.api.nvim_win_close()`
https://github.com/folke/lazy.nvim/issues/81#issuecomment-1363221392

fix(mapping): fix buffer being properly deleted

---

lua/lazy/view/sections.lua

Made it more clear that plugins listed as "Installed" are actually just lazy-loaded plugins that are not loaded.

Changed Header For Plugins Not Loaded to "Not Loaded"

---

lua/lazy/manage/reloader.lua

There is an extra redundant trailing separator in the `root` path in the reloader which also breaks the `fnamemodify` for correctly representing the path to the changed file in the notifcation.
This is how it looks before the change:

fix(reloader): remove extra trailing separator

---

README.md

I'd like to also add a note that makes it clear the plugin's require doesn't have to be the same as the plugin's URL.
I.E:
`folke/trouble.nvim` -> `require('trouble').setup()` and not `require('trouble.nvim').setup()`
`kazhala/close-buffers.nvim` -> `require('close_buffers').setup()` and not `require('close-buffers.nvim').setup()`
I had to try and see if it works even if the name of the plugin differs from the `require()` of it.
Thanks.

docs: fix plugin setup example

---

lua/lazy/view/init.lua

Hi Folke,
Great plugin! Here's a little change to the prompt:
From
to
Note: The default value is already set in the beginning. The original prompt didn't make it clear, that `0` is the default and `0.5` is an example.

chore(ui): nicer threshold prompt

---

lua/lazy/view/commands.lua

`:echo getcompletion('Laz ', 'cmdline')` results in the following error (notice the extra space in 'Laz ')
```
E5108: Error executing Lua function: ...cal/share/nvim/lazy/lazy.nvim/lua/lazy/view/commands.lua:60: attempt to index a nil value                                             
stack traceback:                                                                                                                                                              
...cal/share/nvim/lazy/lazy.nvim/lua/lazy/view/commands.lua:60: in function <...cal/share/nvim/lazy/lazy.nvim/lua/lazy/view/commands.lua:58>             
```

Fix E5108 in getcompletions

---

lua/lazy/help.lua

Example:
```
nui.nvim-popup-lua-nui-popup	nui.nvim.md	/### \[Popup\](lua\/nui\/popup)
```

fix(help): properly escape helptags search pattern

---

README.md
lua/lazy/core/config.lua
lua/lazy/help.lua

I don't know if this PR is gonna be accepted, since I don't see many plugins having multiple `README.md` files in the `lua/` directory.
If it doesn't go with the roadmap or if the `lua/` directory handling seems too specific/hardcoded, feel free to close the PR.

feat(help): accept patterns for readme

---

README.md

It looks like the references to your personal configurations has changed directory structure from `lua/config/plugins` to `lua/plugins`.

fix references to config.plugins

---

lua/lazy/core/config.lua
lua/lazy/view/init.lua

UIs can attach and detach from headless nvim dynamically (indeed, this is one of its use cases).

Don't cache check for attached UIs

---

lua/lazy/view/commands.lua

Set bar attribute:
```
-bar	    The command can be followed by a "|" and another command.
```

Allow commands like `Lazy ... | ...`

---

lua/lazy/view/render.lua

Thanks for this nice plugin manager. I wanted to re-enable `<C-f>` for 'page forward' (https://github.com/folke/lazy.nvim/issues/133#issuecomment-1364299821) and noticed that the help text under `Profile (P)` wasn't updated to reflect the change. This pull request should hopefully fix that.

fix(render): get profile_{sort,filter} key bindings from ViewConfig

---

README.md
lua/lazy/core/config.lua
lua/lazy/core/plugin.lua

Related: https://www.reddit.com/r/neovim/comments/zk187u/how_does_everyone_segment_plugin_development_from/
I used to have a custom use function in packer (Which is no longer possible in lazy.nvim):
```lua
local use = function(opts)
if opts.dev and vim.fn.isdirectory(vim.fn.expand(opts.dev)) ~= 0 then opts[1] = opts.dev end
require("packer").use(opts)
end
use { "catppuccin/nvim", dev = "~/code/git/catppuccin" }
```
With lazy.nvim there's an useful option known as `dev` and it even supports `patterns`! However, I can no longer (easily) sync my config between machines as local plugin dir wouldn't be found
This PR adds an option called `dev.fallback` to fallback to git plugin when local plugin dir doesn't exist

feat(option): fallback to git when local plugin doesn't exist

---

lua/lazy/util.lua

In WSL there is wslview instead of xdg-open.
We can change it by setting it in `ui.browser`, but I think it can be the default choice for WSL.

Use "wslview" instead of "xdg-open" in WSL

---

lua/lazy/core/handler/cmd.lua

Hello, this is just a solution proposal, I hope I don't offend anyone, let alone your fantastic work.
try to fix the bug with the commands defined by `cmd` when executed with a range, as it doesn't accept the count property.
An example of the error is try to lazy load a [Tabular plugin](https://github.com/godlygeek/tabular) 
```lua
{
"godlygeek/tabular",
cmd = {"Tabularize" } 
},
```
Executing the command with a range, for example: `:'<,'>Tabularize /=`, this causes an exception, because the count property is not compatible with range commands:
```
Error executing Lua callback: .../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:34: Command cannot accept a count
stack traceback:
[C]: in function 'cmd'
.../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:34: in function …
```

Fix(Error when triger on range defined command in `cmd`)

---

lua/lazy/util.lua

`vim.fn.executable` returns 0/1 instead of false/true.
Both of 0 and 1 are truthy in lua...

fix executable check

---

lua/lazy/view/float.lua

When `'foldenable'` is `true` the contents of floating window will be folded, which is not convenient.

feat: disable folding of floating window

---

lua/lazy/view/colors.lua
lua/lazy/view/config.lua
lua/lazy/view/render.lua

use `LazyComment` highlight group for commits with housekeeping types, i.e. chore/ci/doc
Inspired by [refined-github](https://github.com/refined-github/refined-github/blob/main/source/features/dim-bots.tsx)

feat(render): dim housekeeping commits by default

---

lua/lazy/manage/git.lua
lua/lazy/manage/task/git.lua

related to https://github.com/folke/lazy.nvim/issues/602, "bug: not all git remotes are called 'origin'"
If honouring global git configs is considered out of scope, lazy can forcibly set the remote name instead

fix(git): always set origin name when cloning

---

lua/lazy/core/cache.lua

On my machine, the current stable branch yields
```
Error detected while processing ~/.config/nvim/init.lua:
E5113: Error while calling lua chunk: ....local/share/nvim/lazy/lazy.nvim/lua/lazy/core/cache.lua:344: attempt
to index a nil value
stack traceback:
....local/share/nvim/lazy/lazy.nvim/lua/lazy/core/cache.lua:344: in function 'lsmod'
....local/share/nvim/lazy/lazy.nvim/lua/lazy/core/cache.lua:251: in function '_find'
....local/share/nvim/lazy/lazy.nvim/lua/lazy/core/cache.lua:272: in function 'find'
....local/share/nvim/lazy/lazy.nvim/lua/lazy/core/cache.lua:131: in function <....local/share/nvim/lazy
/lazy.nvim/lua/lazy/core/cache.lua:129>
[C]: in function 'require'
~/.local/share/nvim/lazy/lazy.nvim/lua/lazy/init.lua:47: in function 'setup'
~/.config/nvim/init.lua:29: in main …
```

fix(cache): fallback path in lsmod

---

README.md

I was originally repeating the plugin name on each spec:
```lua
require("lazy").setup({
spec = {
{ "LazyVim/LazyVim", import = "lazyvim.plugins" },
{ "LazyVim/LazyVim", import = "lazyvim.plugins.extras.ui.mini-starter" },
{ "LazyVim/LazyVim", import = "lazyvim.plugins.extras.coding.copilot" },
},
})
```
Which resulted in the following `checkhealth` warning (at least once I added the second extra plugin:
```
lazy.nvim
- WARNING {LazyVim}: overriding <import>
```
It didn't really occur to me that once the plugin was added, there was no need to specify it again.  You only need to specify the lua module to be imported.  So I figured an example of that would be helpful.

fix(readme): add example of multiple imports

---

lua/lazy/view/render.lua

Hello,
Thanks for your amazing work on `Lazy.nvim`.
This PR adds showing the completely `reason` for `Not Loaded`
Config
```lua
{ 'numToStr/Comment.nvim', lazy = true, keys = { { '<leader>cc' }, { '<leader>cb' }, } },
{ 'fedepujol/move.nvim', lazy = true, cmd = { 'MoveLine', 'MoveBlock', 'MoveHChar', 'MoveHBlock' }, },
```
Before
After Patch

fix(home): show completely `reason` for `Not Loaded`

---

lua/lazy/view/render.lua

When using a local plugin that has not yet been commited, the following error occurs when trying to view plugin information.
```
Error executing vim.schedule lua callback: ...local/share/nvim/lazy/lazy.nvim/lua/lazy/view/render.lua:502: attempt to index field 'commit' (a nil value)
stack traceback:
...local/share/nvim/lazy/lazy.nvim/lua/lazy/view/render.lua:502: in function 'details'
...local/share/nvim/lazy/lazy.nvim/lua/lazy/view/render.lua:422: in function 'plugin'
...local/share/nvim/lazy/lazy.nvim/lua/lazy/view/render.lua:239: in function 'section'
...local/share/nvim/lazy/lazy.nvim/lua/lazy/view/render.lua:71: in function 'update'
.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/view/init.lua:142: in function 'fn'
...tsuuu/.local/share/nvim/lazy/lazy.nvim/lua/lazy/util.lua:72: in …
```

fix(render): show message if not yet committed

---

lua/lazy/core/plugin.lua

Construct the lazy.nvim package's url string using the configured `git.url_format`.
Tested in normal configuration with access to GitHub, and in firewalled situation without GitHub access.

fix(core): use config.git.url_format to build the url for lazy.nvim.  Fixes #791

---

lua/lazy/view/commands.lua

When Lazy commands are searched in command line mode, completion fails horribly (sometime crashing nvim entirely) when the partial string to complete contains non-escape characters.
For example, running `:Lazy up[` results in a crash.
The fix is to instruct string.find to perform a literal search, treating the string to search not as a regular expression.

fix completion error

---

doc/lazy.nvim.txt

From this issue: https://github.com/folke/lazy.nvim/issues/285
Figured it's worth a quick callout in the docs to the alternative approach.

docs: Add example for non-headless sync from CLI

---

README.md
lua/lazy/core/config.lua
lua/lazy/view/render.lua

With this option, user can choose to hide the top row of buttons.

feat(view): add option `ui.button`

---

lua/lazy/core/plugin.lua
tests/core/plugin_spec.lua

Currently, when a plugin is marked with "enabled = false", lazy.nvim investigates the dependencies of that plugin,and disables them when appropriate.
Such behaviour is not implemented for a plugin marked with "optional = true".
Consider a stock LazyVim installation with "extras/lang/python" added to "config/lazy.lua"
The resulting installation includes nvim-dap-python and its keys, but without nvim-dap installed.
Pressing `<leader> d P c` leads to an error.
The UI of which-key shows "prefix" as description for "d".
In "extras/lang/python", nvim-dap-python is a dependency of nvim-dap.
When "extras/dap/core" is not added to "config/lazy.lua", nvim-dap becomes completely optional and will not be installed.
Currently, the dependency of nvim-dap, nvim-dap-python, does get installed.
**Note**: …

feat(plugins): Given an optional plugin, conditionally discard deps

---

README.md

Thanks for your generous guide in #959 , I have read the CI workflow configuration and found that changing `README.md` is actually what I should do.
I have tested this by merge this branch in my fork repo, and it triggered [doc generation](https://github.com/DistinctWind/lazy.nvim-fix-doc-typo/commit/f43331720a53e720c6472077f2fae84736bc19e0) correctly.
---
感谢你在 #959 中的慷慨指导，我阅读了这个项目的CI工作流配置，发现修改`README.md`才是我应该做的。
在镜像仓库中合并该分支，发现确实正确触发了[文档自动生成](https://github.com/DistinctWind/lazy.nvim-fix-doc-typo/commit/f43331720a53e720c6472077f2fae84736bc19e0)。

Fix doc missing bracket

---

lua/lazy/view/init.lua

Sometimes when hovering over updated plugins and triggering `diff` with `d` key, I get an empty `diff` view. I traced the problem to a very generic `commit_pattern` which currently matches any alphanumeric sequence of 7 characters surrounded by "word boundary" / frontier patterns. I adjusted the regex to match only `[a-z0-9] * 7` which should make this issue appear less. I am keeping the older frontier sets `%f[%w]` and `%f[%W]` because if I switch to `%f[a-f0-9]` and `%f[^0-9a-f]` I will be matching strings like `zzz1234567xxx`.

Make commit pattern more accurate

---

lua/lazy/core/plugin.lua
lua/lazy/types.lua
lua/lazy/view/render.lua
tests/core/plugin_spec.lua

Supersedes #1000
Fixes #868
Fixes #1053

feat(plugin): dont include plugin spec fragments for disabled or optional plugins

---

lua/lazy/core/plugin.lua
lua/lazy/types.lua

Example:
```lua
{
{
"folke/tokyonight.nvim",
lazy = true,
opts = { style = "moon" },
},
{
"LazyVim/LazyVim",
priority = 10000,
lazy = false,
opts = {
colorscheme = "tokyonight",
},
version = "*",
import = "lazyvim.plugins",
-- cond = false,
enabled = false,
},
}
```
In this scenario, the `LazyVim` plugin is disabled, and the modules in `lazyvim.plugins` are not loaded.
However, when using `cond = false`, the modules in `lazyvim.plugins` are loaded, disregarding the `cond` setting.
For the [`lazyflex`](https://github.com/abeldekat/lazyflex.nvim) plugin, it makes sense to enable/disable the plugin using `cond`. 
In issue [Simpify installation instructions](https://github.com/abeldekat/lazyflex.nvim/issues/13) the motivation for this PR is described.
This PR adds a check on `cond` to …

feat: on conditional disable, do not import additional plugin modules

---

lua/lazy/manage/lock.lua

Fixes #1093
- fix(manage): preveng auto conversion 'CRLF' to 'LF' in update lazy-lock.json on Windows.

fix(manage): prevend auto conversion 'CRLF' to 'LF'. Fixes #1093

---

README.md
doc/lazy.nvim.txt
lua/lazy/core/config.lua
lua/lazy/view/init.lua
lua/lazy/view/render.lua

Adds an optional description to custom keys. When present, the key is listed in the help menu.
This is how it looks:

feat(keys): include custom keys in help menu

---

lua/lazy/core/loader.lua

See #445
Some options and properties of plugin was not reloaded after `:Lazy reload <plugin>`, because the old version was preserved in cache.

fix(loader): when reloading, clear plugin properties cache

---

lua/lazy/view/render.lua

Before, something like `feat(perl)!:` would not have `(perl)` italicized due to the exclamation point at the end. This PR allows for such commits to have italicized scope as well.

fix: properly highlight breaking change commit scope

---

README.md
lua/lazy/core/config.lua
lua/lazy/core/plugin.lua

In some case, `dev.path .. plugin.name` is not enoguh.
For example, when using `ghq` to manage projects, plugin directories may vary by owners of the plugins.
With this change, users can do something like below
``` lua
require("lazy").setup("plugins", {
dev = {
path = function(plugin)
-- ghq
local path, cnt = string.gsub(plugin.url, "^https://(.*)%.git$", "~/ghq/%1")
if cnt == 1 then
return path
end
-- fallback to default
return "~/projects/" .. plugin.name
end,
},
})
```

feat: support dev.path as function

---

lua/lazy/manage/git.lua

- Modify the condition in the get_config function to correctly ignore comments and blank lines.
- Update the regular expression to exclude lines starting with '#' or ';'.
- This change ensures that only valid key-value pairs are added to the configuration table.

fix(git): comment sign detection in get_config function

---

lua/lazy/core/handler/keys.lua

If the keymap is an abbreviation, just adding an explicit trigger solves the issues (`:h i_CTRL-]`)

fix(keys): fix abbreviation trigger on lazy load (#1218)

---

lua/lazy/types.lua

Without the added parentheses, the type were resolved to
```
(field) keys: (
|string
|LazyKeysSpec[]
|fun(self: LazyPlugin, keys: string[]):string
|LazyKeys[]
|string[]
)?
```
With the paren, it now correctly resolves to
```
(field) keys: (
|string
|LazyKeysSpec[]
|fun(_: LazyPlugin, keys: string[]):(string|LazyKeys)[]
|string[]
)?
```

fix(types): fix incorrect LuaLS types

---

README.md
doc/lazy.nvim.txt
lua/lazy/view/colors.lua
lua/lazy/view/render.lua

Syncs the Tree-sitter highlights to use the new upstream capture groups, as defined by https://github.com/nvim-treesitter/nvim-treesitter/pull/5831

fix: update to new treesitter capture groups

---

lua/lazy/init.lua

The `uv` shim was accidentally set to itself when it was trying to fall back

fix: uv shim was not falling back to vim.loop

---

lua/lazy/view/config.lua

nvim-treesitter has added a bot to automate updating parsers. This feels similar to the other commands that are dimmed.

fix(ui): Add "bot" to dimmed commands list

---

lua/lazy/core/cache.lua

In my config I manually start the cache so I can get some settings files be cached properly, and I had to make these changes to the cache file to get them to work :+1:
EDIT: I think because this code ran before the `vim.uv` value was set from elsewhere in this plugin

fix(cache): vim.loop fallback

---

lua/lazy/view/float.lua

fix(ui): add conditional `nvim_get_hl_by_name` for Neovim 0.8.0

---

lua/lazy/view/commands.lua

opts.plugin can be a list of strings, but currently it would error on not being able to contact the name field
This allows providing a list of strings

fix: strings in lua reload

---

lua/lazy/help.lua

Fix deprecation warning for 0.11

fix: use vim.iter():flatten():totable() over vim.tbl_flatten

---

lua/lazy/view/render.lua

Problem: On current Nvim nightlies, a regression in a
`vim.highlight.range()` refactor makes underlines for diagnostics at end
of line extend into the next line, leading to visual artifacts in the
update view:
(see https://github.com/neovim/neovim/pull/28986)
Solution: Suppress underlines for diagnostics, as they are not wanted
anyway.

fix(render): disable underline for diagnostics

---

lua/lazy/core/config.lua
lua/lazy/core/loader.lua
tests/core/util_spec.lua

There is an issue in the `neodev` repo that mentions this: [#193](https://github.com/folke/neodev.nvim/issues/193)
I think the problem comes from a combination of 2 things:
1. As mentioned in the [Reddit post](https://www.reddit.com/r/neovim/comments/1cvrilk/diagnosticwarning_after_upgrade_to_neovim_010/): `Nvim never had Lua type annotations for vim.opt`.
2. Setting `vim.opt.rtp` anywhere in the config will cause Lua-LS to infer the type for `vim.opt.rtp`. While users are unlikely to do this it does happen in `lazy.nvim`, in places shown in this PR.
There are some longer term plans to remove `vim.opt` in general: https://github.com/neovim/neovim/issues/20107.
In the meantime setting the `type` annotation seems like a good enough hack, while it's the suggested setup in the README.
Totally …

Set vim.opt.rtp type to vim.Option

---

README.vim.md
docs/spec/lazy_loading.md

This is minor but it tripped me up for a bit. I was setting all my colorschemes to lazy load without realizing that it was negating the `priority` option altogether. The statement explaining that colorschemes *can* be lazy loaded with `lazy = true` followed immediately by a note about setting the `priority` for your main colorscheme seemed to imply that the specified priority would work with lazy loaded colorschemes.
This PR just adds the clarification that a "start plugin" implies `lazy=false`. It's just the same clarification that is already used for the `priority` description.

fix(docs): Minor clarification.

---

lua/lazy/manage/checker.lua
lua/lazy/manage/git.lua
lua/lazy/manage/task/git.lua

As I described in https://github.com/folke/lazy.nvim/pull/1512#issuecomment-2212474372, this makes it so that local plugins will only show as needing updates if the local branch is behind the upstream branch. This is done by checking the output of the `git log` command, and only setting `plugin._.updates` if the output is not empty.
This seems to solve my issue where local plugins with unpushed changes always show as needing updates, but if there's a easier/better way of doing it then please feel free to edit/close this. Or if you don't agree that the current behaviour is a bug, then that's also fine - it's not a big deal and I can easily just ignore the "updates available" notice.
I also came across a minor issue where the plugin diff view (press `d`) compares the wrong commits for local …

fix(git): local plugin fixes

---

lua/lazy/manage/lock.lua

The lockfile currently does not end with a newline at EOF. Text files should [end with a newline](https://unix.stackexchange.com/a/18789). This also lets you manually edit the lockfile in vim without 'fixeol' creating a spurious change for the added newline.
This change however will create a change in users' lockfiles adding a newline upon updating, but since the lockfile would be changing anyways to update lazy.nvim itself, this is likely acceptable.
*none*
*N/A*

fix(lockfile): ensure newline at EOF for lockfile

---

doc/lazy.nvim.txt

After a discussion on Slack we noticed that the description of the sync command is a bit vague. Some people, including myself, assumed `clean`/`install`/`update` referred to build steps being performed per plugin.
Another person mentioned they thought it referred to the Lazy commands, which does make more sense.
They also noticed that the order of the commands do not match the source code.
So this PR corrects the order, assuming it was meant to be ordered, and mentions that those are commands for clarity.

docs(commands): fix command ordering for sync

---

lua/lazy/manage/task/plugin.lua

On plugins update it fails with following error for any plugin.
```
~/.local/share/nvim/lazy/lazy.nvim/manage/task/plugin.lua:95: Vim:E150: Not a directory: ~/.local/share/nvim/lazy/gitsigns.nvim/doc/
```

fix(plugins): "Vim:E150: Not a directory" on plugin update

---

lua/lazy/core/config.lua

In the issue (#1707) I was confused by the description of `dev.path`. I thought functions must also return the general directory for local plugins, but it must be the plugin directory.
#1707

chore(config): update dev.path description

---

lua/lazy/core/loader.lua

`package.cpath` is missing the `lib64` directory for plugins that have luarocks dependencies.
I found this issue when I was working on my new Neovim plugin on my Fedora 39 machine. I added the `luasockets` dependency to rockspec file in my plugin like so:
```
rockspec_format = "3.0"
package = "typeracer.nvim"
version = "scm-1"
source = {
url = "git+https://github.com/carbon-steel/typeracer.nvim",
}
dependencies = {
"luasocket",
}
test_dependencies = {
"nlua",
}
build = {
type = "builtin",
copy_directories = {},
}
```
I found that the dynamic libraries from the `luasockets` dependency were installed like so: `/home/username/.local/share/nvim/lazy-rocks/typeracer.nvim/lib64/lua/5.1/socket/core.so`. However, the only entry related to my plugin `typeracer.nvim` was: …

fix(rocks): add lib64 plugin directory to package.cpath

---

lua/lazy/pkg/rockspec.lua

When passing the `--dev` flag to `luarocks`, it will prioritise `dev` versions when resolving dependencies (treating `dev` or `scm` as greater than a SemVer version) if the rockspec doesn't specify an upper version constraint (which is often the case).
Dev packages are often unstable and may cause more problems, especially for Windows users (an example I've seen is git for windows trying and failing to checkout submodules).
For now , a good compromise between too many retries and not retrying at all could be to try `luarocks install` from the root manifest first, but to keep the `--dev` flag in `luarocks make`.
If that still causes problems, it might be better to fall back to `luarocks make` without `--dev` first, and then to try `luarocks ---dev make` as a last resort.
In rocks.nvim, we …

fix(luarocks): try to install from root manifest

---

lua/lazy/view/commands.lua

Problem: Command completion doesn't work if the command name isn't written in full
Solution: Use vim.startswith to check if the command is a prefix of 'Lazy'
Fixes #1758

fix(completion): check if command string is a prefix of Lazy

---

lua/lazy/types.lua

> After updating lua_ls to [v3.13.3](https://github.com/LuaLS/lua-language-server/releases/tag/3.13.3) noticed my plugin scripts using `@type LazyPluginSpec` now have `missing-fields` warnings.
It seems they have changed how `missing-fields` diagnostics work with inherited types: https://github.com/LuaLS/lua-language-server/commit/7b2d58537fea87d1fefec894ac17b3bd73681e63.
Duplicate offending fields as optional in type `LazyPluginSpec`
Closes: #1842

fix(types): ensure all fields for `LazyPluginSpec` are optional

---

lua/lazy/core/config.lua
lua/lazy/view/render.lua

lazy.nvim allows users to configure all icons except for the debug icon. This PR enables user to configure the debug icon with `ui.icons.debug`
Before:
After (with config `{ ui = { icons = { debug = ' ' } } }`):

feat(config,render): allow customizing the debug icon

---

lua/lazy/view/render.lua

https://github.com/neovim/neovim/pull/31959 has introduced virtual lines for showing diagnostics. If this is enabled (default value), messages from lazy.nvim, such as `update available` are shown as virtual lines in addition to virtual texts.
* ***before***
- <img width="592" alt="スクリーンショット 2025-01-27 16 42 27" src="https://github.com/user-attachments/assets/6994ac84-4862-4532-81ee-80f4015181e5" />
* ***after***
- <img width="585" alt="スクリーンショット 2025-01-27 16 42 58" src="https://github.com/user-attachments/assets/d19f63dc-fb6d-434f-89cf-a0bc49d31c5f" />

fix(ui): do not show virt_lines for messages

---

lua/lazy/core/handler/keys.lua

when `expr=true` the rhs function should return a string.
example
```lua
{
keys = {
{
'<leader>j',
function()
return require('dial.map').inc_normal()
end,
expr = true,
desc = 'Increment value',
}
}
}
```

fix(types): add optional return value for `LazyKeysSpec` rhs
